const conditionList = [
    {
      "id": "and",
      "Name": "AND"
    },
    {
      "id": "or",
      "Name": "OR"
    }
  ];
  const newPedigreeWithMHData = [ 
    [
        {
            "tag": "MH",
            "horseData": {
            "horseId": null,
            "horseName": null,
            "sex": null,
            "yob": null,
            "countryId": null,
            "colourId": null,
            "gelding": null,
            "isLocked": null,
            "horseTypeId": null,
            "cob": null,
            "G1Tag": null,
            "G1TagFull": null,
            "isVerified": null,
            "progenyId": null,
            "legendColor": null
            }
        }
    ],     
  [
    {
      "tag": "S",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": "+add",
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "D",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": "+add",
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    }
  ],
  [
    {
      "tag": "SS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    }
  ],
  [
    {
      "tag": "SSS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SSD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SDS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SDD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DSS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DSD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DDS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DDD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    }
  ],
  [
    {
      "tag": "SSSS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SSSD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SSDS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SSDD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SDSS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SDSD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SDDS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SDDD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DSSS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DSSD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DSDS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DSDD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DDSS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DDSD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DDDS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DDDD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    }
  ],
  [
    {
      "tag": "SSSSS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SSSSD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SSSDS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SSSDD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SSDSS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SSDSD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SSDDS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SSDDD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SDSSS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SDSSD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SDSDS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SDSDD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SDDSS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SDDSD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SDDDS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "SDDDD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DSSSS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DSSSD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DSSDS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DSSDD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DSDSS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DSDSD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DSDDS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DSDDD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DDSSS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DDSSD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DDSDS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DDSDD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DDDSS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DDDSD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DDDDS",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    },
    {
      "tag": "DDDDD",
      "olduuid": null,
      "newuuid": null,
      "horseData": {
        "horseId": null,
        "horseName": null,
        "sex": null,
        "yob": null,
        "countryId": null,
        "colourId": null,
        "gelding": null,
        "isLocked": null,
        "horseTypeId": null,
        "cob": null,
        "G1Tag": null,
        "G1TagFull": null,
        "isVerified": null,
        "progenyId": null,
        "legendColor": null
      }
    }
  ]
];  
export const horsefilterConstants = {
    duplicateSettingList : conditionList,
    blankPedigreeData : newPedigreeWithMHData,
  }