export type RaceHorse = {
    id: any;
    farmName: string;
    countryId: number;
    countryCode: string;
    stateId: number;
    stateName: string;
    website: string;
    totalStallions: number;
    promoted: number;
    users: number;
    received: number;
    sent: number;
    lastActive: string;
    isActive: boolean;
    isImported: boolean;
    countryName: string;
    createdOn: string;
    currencyId: number;
    damId: string;
    damName: string;
    damCountryCode: string;
    damYob: number;
    dob: number;
    horseId: string;
    horseName: string;
    isVerified: boolean;
    sex: string;
    sireId: string;
    sireName: string;
    sireCountryCode: string;
    sireYob: string;
    yob: number;
    raceUuid:string;
    raceName:string;
    raceHorseId: string;
    raceHorseUrl: string;
    url: string;
    mainDate: string;
  };