export type Races = {
  id: string;
  raceId:number;
  noOfRaces: number;
  venue: string;
  country: string;
  countryName: string;
  name: string;
  raceName: string;
  class: string;
  trackType: string;
  apiStatus: string;
  runners: number;
  isImported: boolean;
  raceDate: string;
  time: string;
  trackCondition: string;
  distance: number;
  distanceUnit: string;
  stakes: string;
  ageRestriction: number;
  sexRestriction: string;
  currency: string;
  prizeMoney: number;
  raceStatus: string;
  raceType: string;
  isEligible: boolean;
  displayName: string;
  venueId: number;
  racePrizemoney: number;
  raceSexRestrictionId: number;
  raceStakeId: number;
  raceStatusId: number;
  raceTime: string;
  raceTypeId: number;
  raceWeatherId: number;
  sourceId: number;
  trackConditionId: number;
  trackTypeId: number;
  raceAgeRestrictionId: number;
  raceClassId: number;
  distanceUnitId: number;
  totalRunner:number;
  currencyId:number;
  importedName:string;
  racestatus:string;
  raceUuid:string;
  countryCode:string;
  countryId:number;
  racenumber:number;
};