import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { api } from 'src/api/apiPaths';

const accessToken = localStorage.getItem('accessToken');

export const emptySplitApi = createApi({
  reducerPath: 'splitApi',
  baseQuery: fetchBaseQuery({
    baseUrl: 'https://',
  }),
  tagTypes: [
    'Breed',
    'Login',
    'forgot-Password',
    'resend-confirm-email',
    'horses',
    'stallions',
    'stallion',
    'member',
    'Colour',
    'Currency',
    'Country',
    'States',
    'StallionAutocomplete',
    'Promotionstatus',
    'Feestatus',
    'Feeupdatedby',
    'FarmAutocomplete',
    'RetiredReason',
    'HorseTypes',
    'PaymentMethods',
    'SocialLinks',
    'notifications',
    'NotificationTypes',
    'farm',
    'race',
    'runner',
    'setting',
    'sm-setting',
    'marketingHome',
    'marketingTrends',
    'marketingFarm',
    'marketingStallion',
    'marketingRacehorse',
    'marketing',
    'farmAccessLevel',
    'pricing-tile',
    'promoCodes',
    'products',
    'users',
    'category',
    'horse-name-alias',
    'horse-cob-alias',
    'messages',
    'conversationMessage',
    'userManagement',
    'stallions-service-fees',
    'stallion-matched-mare',
    'progeny-tracker',
    'key-words-search',
    'horse-name-default-alias',
    'horse-cob-default-alias',
    'sale',
    'app-dashboard',
    'progeny-tracker-sr',
    'matched-mares',
    'marketingReportsOverview',
    'media-status',
    'marketingStallionPageTestimonialTag',
    'marketingFarm',
    'marketing farm media',
    'marketingFarmGallery',
    'marketing stallion',
    'key-statistics',
    'close-analytics',
    'fee-history',
    'match-activity',
    'member status',
    'page-settings',
    'report',
    'systemActivity',
    'app-permission',
    'raceHorses',
    'user profile'
  ],
  endpoints: () => ({}),
});

export const splitApi = emptySplitApi;
